"""empty message

Revision ID: ee647079b0e5
Revises: 
Create Date: 2021-11-09 12:03:47.713780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee647079b0e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fin_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('open_data', sa.Float(), nullable=True),
    sa.Column('high_data', sa.Float(), nullable=True),
    sa.Column('low_data', sa.Float(), nullable=True),
    sa.Column('close_data', sa.Float(), nullable=True),
    sa.Column('adj_close_data', sa.Float(), nullable=True),
    sa.Column('volume_data', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fin_data')
    op.drop_table('company')
    # ### end Alembic commands ###
